name: Jar-Maker

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-1st:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'    
    - name: Create Jar
      run: |
        javac MyApp/InPut.java
        javac MyApp/OutPut.java
        jar -cfvm MyApp.jar META-INF/MANIFEST.MF MyApp/OutPut.class MyApp/InPut.class
        javac ExecuteApp/InPut.java
        javac ExecuteApp/OutPut.java
        jar -cfvm ExecuteApp.jar ExecuteApp/manifest.txt ExecuteApp/OutPut.class ExecuteApp/InPut.class
        ls -l        
    - name: Test Jar
      run: |        
        java -jar MyApp.jar
        java -jar ExecuteApp.jar
        sudo bash mpstat.sh
    - name: Upload release asset ${{env.strDate}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.jar
        tag: MyApp
        file_glob: true
        overwrite: true
        release_name: MyApp       
    - name: Clean Readme
      run: |
        rm README.md
        date >> README.md         
    - name: Commit
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Update File"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
